# Generated by Django 4.1.4 on 2022-12-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=100)),
                ('salary', models.PositiveIntegerField()),
                ('experience', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('roles_responsibilities', models.TextField(max_length=500)),
                ('about_company', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=150)),
                ('pincode', models.PositiveIntegerField()),
            ],
        ),
    ]
