# Generated by Django 4.1.4 on 2022-12-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_useraccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
