# Generated by Django 4.1.4 on 2022-12-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_useraccount', '0006_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='profile',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
