# Generated by Django 4.1.4 on 2022-12-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_useraccount', '0008_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_category',
            name='icon',
            field=models.FileField(null=True, upload_to='media/job_category/icon'),
        ),
    ]
