# Generated by Django 4.1.4 on 2022-12-20 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_useraccount', '0009_job_category_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_category',
            old_name='icon',
            new_name='img',
        ),
    ]
