# Generated by Django 4.1.4 on 2022-12-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_useraccount', '0010_rename_icon_job_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='media/job_profile_pic/'),
        ),
        migrations.AlterField(
            model_name='job_category',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='media/job_category/icon'),
        ),
    ]
