# Generated by Django 4.1.4 on 2022-12-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_useraccount', '0014_alter_job_post_posted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='posted_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
