# Generated by Django 4.1.4 on 2022-12-22 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_useraccount', '0016_alter_job_post_jobholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='jobholder',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
