# Generated by Django 4.1.4 on 2022-12-22 08:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_useraccount', '0018_rename_profile_candidate_profile_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Candidate',
            new_name='CandidateProfile',
        ),
    ]
