# Generated by Django 4.1.4 on 2022-12-22 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_useraccount', '0019_rename_candidate_candidateprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
