# Generated by Django 4.1.4 on 2022-12-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_useraccount', '0020_delete_appuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.PositiveIntegerField()),
                ('post_for_apply', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
    ]
