# Generated by Django 4.1.4 on 2022-12-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_useraccount', '0021_job_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='about_me',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
