# Generated by Django 4.1.4 on 2022-12-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_useraccount', '0022_candidateprofile_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='expected_ctc',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
