# Generated by Django 4.1.4 on 2022-12-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_useraccount', '0023_candidateprofile_expected_ctc'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='preferred_location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
